### ISSUE TITLE
Створення команд та репозиторію проекту (ІП-4Х, 3 курс)

### ISSUE THREAD

**Issue by GYFK** [kpimobiledev/MobileDev#1]
Написати у коментарі до issue:

- Cписок розробників у команді з посиланнями на їх сторінки у Github
- Платформа або платформи на яких буде проводитись розробка 
- Технологія розробки 
- Посилання на репозиторій у Github

Зробити у вигляді: 

| People | Platforms | Technology |  Link |
| :------: | :--------: | :-----------: | :---: |
|  [Artem Chernenkiy](https://github.com/GYFK) | iOS  |  Swift |  [kpimobiledev/MobileDev](https://github.com/kpimobiledev/MobileDev) | 
| [Lidiya Ivanova](https://github.com/lidaamber) | Android | Java | |
| [Andriy Oleksiy](https://github.com/olecsiuyae)| iOS / Android | Xamarin | |

Термін виконання: до 24.02.

**Comment by DmytroKanivets** [comment]
People | Platforms | Technology | Link
-------|----------|---------|---------
[Olexiy Miroshnyk](https://github.com/OlexMir) | Android | Java | [TopDevs/AIMer](https://github.com/TopDevs/AIMer)
[Dmytro Kanivets](https://github.com/DmytroKanivets) | Android | Java |

**Comment by AnnaSamonenko** [comment]
People | Platform | Technology | Link
------------ | ------------- | ------------- | -------------
[Anna Samonenko](https://github.com/AnnaSamonenko) | Android | Java | [K/S](https://github.com/AnnaSamonenko/kIs-music-player/settings)
[Lena Kasym](https://github.com/KeilyLou) |  | Android | Java |

**Comment by romanusyk** [comment]
People | Platform | Technology | Link
---------|-------------|----------------|------
[Roman Usyk](https://github.com/Romm17/)| Android | Java | [Romm17/FriendTreasury](https://github.com/Romm17/FriendTreasury)
[Yurii Krat](https://github.com/YuriiKrat)| Android | Java |
[Bohdan Romanchuk](https://github.com/RBV1/)| Android | Java |

**Comment by MrVladis1av** [comment]
**People**|**Platform**|**Technology**|**Link**
-----------|--------------|-----------------|-----------
[Vladislav Stetsenko](https://github.com/MrVladis1av)|Android|Java|[MrVladis1av/EventService](https://github.com/MrVladis1av/EventService)
[Viacheslav Demianenko](https://github.com/Dreadful0)|Android|Java|

**Comment by TanyaOhotnik** [comment]
| People      | Platform         |Technology  |Link|
| ------------- |-------------| -----|-----|
| [Tanya Ohotnik](https://github.com/TanyaOhotnik)   | Android | Java | [MoneyControlAndroid](https://github.com/TanyaOhotnik/MoneyControlAndroid)|
| [Olga Saliy](https://github.com/OlgaSaliy)    | iOS      |   Objective-C |[MoneyControliOS](https://github.com/olgasaliy/MoneyControliOS)|

**Comment by VitaliyVinterle** [comment]
| People | Platform | Technology | Link |
| ------ | ------ | ------ | ------ |
| [Vitaliy Vinterle](https://github.com/VitaliyVinterle) | Android | Java | [VitaliyVinterle/AndroidCourseApp](https://github.com/VitaliyVinterle/AndroidCourseApp) |

**Comment by yaroslavOshyyko** [comment]
People | Platform | Technology | Link 
------------ | ------------- | ---------- | ---
[Yaroslav Oshyyko](https://github.com/yaroslavOshyyko) | Android | Ionic 2 | [your-city-portal](https://github.com/yaroslavOshyyko/your-city-portal)
[Andrey Zubritskiy](https://github.com/zubr13) | Android | Ionic 2  |

**Comment by mitchsvik** [comment]
| People | Platform | Technology | Link |
|-|-|-|-|
|[Veniamin Zinevych](https://github.com/mitchsvik)|Android|Java|[Shakalizator](https://github.com/mitchsvik/shakalizator)

**Comment by ghost** [comment]
| People | Platform | Technology | Link |
| ------ | ------ | ------ | ------ |
| Vlad Brazhnik | Android | Java | [Tracker: ToDo's and Routines](https://github.com/VBrazhnik/Tracker-ToDo-s-and-Routines) |

**Comment by GYFK** [comment]
@mitchsvik репозиторій приватний, тож не надто зручно його переглядати. До того ж, не думаю, що це підходить як назва курсової роботи.

**Comment by mitchsvik** [comment]
@GYFK репозиторій публічний і був публічним. Назва робоча. До релізу документації може змінитися. 
Курсова робота у нашої кафедри з паралельного програмування.

**Comment by GYFK** [comment]
@mitchsvik прошу пробачення, посилання було неробочим через наявність зайвого символу, з чого і зробив даний висновок. Вашу відповідь я відредагував. Вимоги до курсової роботи (саме як результату вивчення курсу) не відрізняються нічим, крім необхідності написання протоколу до неї тим, у кого оцінка йде у заліковку. Проте залишаю це питання на ваш розсуд.

**Comment by YevheniiStepaniuk** [comment]
People| Platform| Technology | Link
------------ | ------------- | ------------- | -------------|
[Yevhenii Stepaniuk](https://github.com/yevheniyStepaniuk) | Android | Java |  [Rozklad](https://github.com/yevheniyStepaniuk/Rozklad)
[Vadym Mazur](https://github.com/MazurVadym) | Android | Java | 
[Valoviy Miroslav](https://github.com/dEsh7) | Android | Java |

**Comment by Greemjoy** [comment]
People | Platform | Technology | Link
------------ | -------------| -------------| -------------
[Alexander Khaukha](https://github.com/Greemjoy) | Android | Java | [purpleHaze](https://github.com/Greemjoy/purpleHaze)
[Alexey Bozhko](https://github.com/BozhkoAlex) | Android | Java | :shipit:
[Denis Putilin](https://github.com/BazingoW) | Android | Java |

**Comment by BaranovYaroslav** [comment]
People | Platform | Technology | Link
-------|----------|------------|------
[Yaroslav Baranov](https://github.com/BaranovYaroslav) | Android  | Java | [foods-plus](https://github.com/BaranovYaroslav/foods-plus-android) 
[Oleg Klisch](https://github.com/Acarus) | Android | Java | 
[Yuriy Romanovskiy](https://github.com/Romanovskiy) | Android | Java |

**Comment by bogdanKaftanatiy** [comment]
<table>
        <tr align="center">
            <td><strong>People</strong></td>
            <td><strong>Platform</strong></td>
            <td><strong>Technology</strong></td>
            <td><strong>Link</strong></td>
        </tr>
        <tr>
            <td><a href="https://github.com/bogdanKaftanatiy" >Bogdan Kaftanatiy </a></td>
            <td>Android</td>
            <td>Java</td>
            <td><a href="https://github.com/bogdanKaftanatiy/ConquerorApp">ConquerorApp</a></td>
        </tr>
        <tr>
            <td><a href="https://github.com/mrLordi" >Denys Vodotiiets </a></td>
            <td>Android</td>
            <td>Java</td>
            <td></td>
        </tr>
        <tr>
            <td><a href="https://github.com/ParamonovNazar">Nazar Paramonov</a></td>
            <td>Android</td>
            <td>Java</td>
            <td></td>
        </tr>
</table>

**Comment by snanovskyi** [comment]
| People | Platform | Technology | Link |
| ------- | -------- | ------------ | ---- |
| [Sergey Nanovsky](https://github.com/sun1x) | [PWA](https://en.wikipedia.org/wiki/Progressive_web_app) | JavaScript | [Timetable](https://github.com/sun1x/timetable) |
| [Julia Shurygina](https://github.com/mynameisjulia) | [PWA](https://en.wikipedia.org/wiki/Progressive_web_app) | JavaScript | [Timetable](https://github.com/sun1x/timetable) |

**Comment by mashkovskiy** [comment]
People| Platform | Technology | Link
------------ | ------------- | ------------- | -------------
[Anton Mashkovsky ](https://github.com/mashkovskiy)| Android | C#|[RunSlothyRun](https://github.com/mashkovskiy/RunSlothyRun)
[Oleg Hrapov](https://github.com/OlegHrapov) | Android | C#

**Comment by Poddiachyi** [comment]
<table>
<tr align='center'><th>People</th><th>Platform</th><th>Technology</th><th>Link</th></tr>
<tr align='center'><td><a href="https://github.com/LeraSavchenko">Sava</a></td><td>Android</td><td>Java</td><td><a href="https://github.com/LeraSavchenko/Mobile">INSTALOOK</td></tr>
<tr align='center'><td><a href="https://github.com/Poddiachyi">Hound</a></td><td>Android</td><td>Java</td><td></td></tr>
</table>

**Comment by IvanEh** [comment]
| People                                      | Platforms | Technology | Link                                     |
|---------------------------------------------|-----------|------------|------------------------------------------|
| [Ivan Ehreshi](https://github.com/IvanEh)   | Android   | Java       | https://github.com/IvanEh/narratilizator |
| [Vita Karas'](https://github.com/VitaKaras) | Android   | Java       |                                          |
| [Yuriy Sych](https://github.com/SichYuriy)  | Android   | Java       |                                          |

**Comment by JekaK** [comment]
People  | Platform | Technology | Link 
--------|----------|------------|------
[Eugeniy Krukun](https://github.com/JekaK) | Android  | Java       | https://github.com/JekaK/PicturePlease
[Kyryl Kurylchenko](https://github.com/Verrden)  | Android  | Java       |

**Comment by AndreiChernata** [comment]
People | Platform | Technology | Link 
[Andriy Chernata](https://github.com/AndreiChernata) | Android | Java | https://github.com/AndreiChernata/Taxi

**Comment by andriiChernata** [comment]
People | Platform | Technology | Link 
-------- | ---------- | ------------ | -----------
[Andriy Chernata](https://github.com/AndreiChernata) | Android | Java | https://github.com/AndreiChernata/Taxi

**Comment by hellomisterbro** [comment]
| People | Platform | Technology |Link|
|     :---:      |     :---:      |     :---:      |     :---:      |
| [Mykyta Kyrychek](https://github.com/nikitakirichek)   | iOS | Swift  |https://github.com/TableBooking/ios-client |
| [Maria Kozliuk](https://github.com/MariaKozlyuk) | iOS | Swift |
| [Anatoliy Bernatovich](raixur@gmail.com) | iOS | Swift |

**Comment by alinkedd** [comment]
| People | Platform | Technology  | Link |
| --------- |------------ | ---------------- | -----  |
| [Alina Listunova](https://github.com/alindos) | iOS / Android | NativeScript | [divinj](https://github.com/alindos/divinj) |
| [Alexey Orlenko](https://github.com/aqrln) | iOS / Android | NativeScript | |

**Comment by AleksFinch** [comment]
People |Platform|Technology| Link
------------ | ------------- | ------------- | -------------
[Olexandr Finchuk](https://github.com/AleksFinch) | Android | Java | [Most reliable alarm](https://github.com/AleksFinch/MostReliableAlarm)  or [Save your cash](https://github.com/AleksFinch/SaveYourCash)

**Comment by belochub** [comment]
| People | Platforms | Technology | Link |
|--------|-----------|------------|------|
| [Mykola Bilochub](https://github.com/belochub) | Android | Java / Golang | [belochub/upspin-android](https://github.com/belochub/upspin-android) |

**Comment by yehorb** [comment]
| People | Platforms | Technology | Link |
| --- | --- | --- | --- |
| [Yehor Borkov](https://github.com/YehorBorkov) | Android | Java | [Emotions Tracker](https://github.com/YehorBorkov/Emotions-Tracker) |

**Comment by vlfom** [comment]
People | Platforms | Technology | Link |
----------------------------|-----------------|------------------|-----|
[Volodymyr Fomenko](http://github.com/vlfom) | Android | Java | [WordGraph](https://github.com/vlfom/WordGraph) |

**Comment by primeare** [comment]
People | Platforms | Technology | Link
------ | --------- | ---------- | ----
[Vladyslav Dukhin](https://github.com/primeare) | Android | Xamarin | [Weather App](https://github.com/primeare/WeatherApp-edu)
[Mikhail Demidoff](https://github.com/thundermind) | Android | Xamarin | 
[Nikita Silkin](https://github.com/silkin) | Android | Xamarin |

**Comment by BodyaWestSide** [comment]
| People        | Platforms           | Technology  | Link |
| ------------- |:-------------:| -----:| ----------:|
| [Bogdan Bezgubenko](https://github.com/bodyawestside)     | Android/iOS| unity | [LA soul](https://github.com/BodyaWestSide/LA_soul) |
| [Max Bormotov](https://github.com/jastplusfour)     | Android/iOS    |   unity | |

**Comment by shabanovd97** [comment]
| People | Platforms | Technology | Link |
| ------- | --------- | ----------- | ------ |
| [Dmitry Shabanov](https://github.com/DmitryShabanov) | Android | Java | [LifeTasks](https://github.com/DmitryShabanov/LifeTasks) |
| [Oleg Dmitryuk](https://github.com/OlegDmitryuk) | Android | Java |
| [Eugeniy Kamensky](https://github.com/Kaskyi) | Android | Java |

**Comment by DzyubSpirit** [comment]
| People | Platforms | Technology | Link |
| --- | --- | --- | --- |
| [Vlad Dzyuba](https://github.com/DzyubSpirit/) | Andriod | Java | [Mobile course work](https://github.com/DzyubSpirit/mobile_course_work) |

**Comment by lidaamber** [comment]
@AleksFinch давай [MostReliableAlarm](https://github.com/AleksFinch/MostReliableAlarm), поскольку второй проект на самом деле очень сложный в общем срезе проектов, а за обе идеи +.

**Comment by lidaamber** [comment]
Те, кто не добавил, use-case или описание, сделайте это, пожалуйста.

**Comment by GYFK** [comment]
@yevheniyStepaniuk @BodyaWestSide @mitchsvik @Poddiachyi @AndreiChernata @alindos @DzyubSpirit @DmitryShabanov @vlfom @belochub Напоминание: обновите/добавьте описание.

**Comment by AndreHollow** [comment]
| People  | Platforms | Technology  | Link |
| ------------- | ------------- | ------------- | ------------- |
| [Elena Kozel](https://github.com/KozelElena) | IOS | Swift  | [JunDev](https://github.com/AndreHollow/TerminKalender/blob/master/README.md)  |
| [Andrey Semerenko](https://github.com/AndreHollow)  | IOS | Swift  |   |
| [Jury Nishchenko](https://github.com/post-Industrial/)  | IOS | Xamarin |   |

**Comment by Igor4204** [comment]
<html>
 <head>
 </head>
 <body>
  <table border = "0" cellspacing = "0">
   <tr>
    <td align = "center"><b>People</b></td>
    <td align = "center"><b>Platform</b></td>
    <td align = "center"><b>Technology</b></td>
    <td align = "center"><b>Link</b></td>
   </tr>
   <tr>
    <td align = "center"><a href = "https://github.com/Igor4204">Igor Gerasimenko</a></td>
    <td align = "center">Android</td>
    <td align = "center">Java</td>
    <td align = "center"><a href = "https://github.com/Igor4204/Messenger">Messenger</a></td>
   </tr>
  </table>
 </body>
</html>

**Comment by Gambit12** [comment]
People | Platform | Technology | Link
------------ | ------------- | ----------------- | ---------
[Anna Samonenko](https://github.com/AnnaSamonenko) | Android | Java | [kIs](https://github.com/AnnaSamonenko/kIs-music-player/)
[Lena Kasym](https://github.com/KeilyLou) | Android | Java | 
[Arkadiy Maklakov](https://github.com/Gambit12) | Android | Java |

**Comment by GYFK** [comment]
@AnnaSamonenko удалите один из комментариев:
https://github.com/kpimobiledev/MobileDev/issues/1#issuecomment-284887622
https://github.com/kpimobiledev/MobileDev/issues/1#issuecomment-281077112

**Comment by MortarionUA** [comment]
| People | Platform | Technology | Link |
--- | --- | --- | ---
| [Dmytro Shcherbakov](https://github.com/MortarionUA) | Android | Java | [PhotoMap](https://github.com/MortarionUA/PhotoMap) |
| [Serhiy Dmitrik](https://github.com/DmitrikSerhiy) | Android| Java |  |
